"""Write NARRATION.md: every scene's timing, on-screen text and voice-over, from demo.json and the build timeline."""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
demo = json.load(open(os.path.join(here, 'demo.json')))
timeline = json.load(open(os.path.join(here, demo['work_dir'], 'timeline.json')))
durs = {s['id']: s['dur'] for s in timeline['scenes']}
fade = demo.get('crossfade', 0.6)

rows, t = [], 0.0
for sc in demo['scenes']:
    d = durs.get(sc['id'], 0)
    on_screen = sc.get('head') or sc.get('tagline') or ' / '.join(sc.get('lines', []))
    shows = sc.get('src', sc.get('image', 'diagram' if sc.get('diagram') else ''))
    rows.append(f"| {int(t // 60)}:{t % 60:04.1f} | {sc['id']} | {shows} | {on_screen} | {sc['vo']} |")
    t += d - fade
total = t + fade

out = [
    '# EarnX pitch video: narration',
    '',
    f'Length {int(total // 60)}:{total % 60:04.1f}. Generated by `make_table.py` from `demo.json`; edit that file and rebuild.',
    '',
    '| Starts | Scene | Shows | On screen | Voice-over |',
    '|---|---|---|---|---|',
    *rows,
    '',
]
open(os.path.join(here, 'NARRATION.md'), 'w').write('\n'.join(out))
print('\n'.join(out[:3]))
